[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "FosCat"
authors = [{name = "Delouis", email = "jean.marc.delouis@ifremer.fr"},{name = "Foulquier", email = "theo.foulquier@ifremer.fr"}]
dynamic = ["version", "description"]
